### ISSUE TITLE
Sound And Mic doesn't work during calls 

### ISSUE THREAD

**Issue by RemonAbdelmalak** [DeadSquirrel01/android_device_samsung_a5-common#10]
when someone call me I can't hear him and he can't too
please tell me how to fix this 
SM-A500H
thanks for your time :)

**Comment by iijhay2** [comment]
Try following this instructions:

1. Download "Disable Service app" ( https://play.google.com/store/apps/details?id=cn.wq.disableservice ) from PlayStore.

2. Search for Google Play Services and disable the CheckInService specifically by unchecking the tick box.

3. Reboot

Credits : Krishna Sagar

**Comment by RemonAbdelmalak** [comment]
Sorry but it didn't help  :(

**Comment by knuxify** [comment]
You might want to try another rom for now. I know one rom made for A500H (RR Rom for A500H/A500XX) so you might want to check it out.

You can also try re-installing the rom

**Comment by DeadSquirrel01** [comment]
Fixed with https://github.com/DeadSquirrel01/android_device_samsung_a5-common/commit/83bb8f906922d695798bb8ab4b2df1333c757a58
