### ISSUE TITLE
SIM Card is not detected.

### ISSUE THREAD

**Issue by RezaKargar** [DeadSquirrel01/android_device_samsung_a5-common#12]
My phone is A500f and I installed Lineage os 14.1 on it but there is a bug , Rom doesn't recognize SIM card .
What can I do?

**Comment by knuxify** [comment]
> Have you replaced libsecril.so and if it is multisim also libsecril-dsds.so from stock rom with the one(s) in recovery? (If it is multisim you have to add in build.prop persist.radio.multisim.config=dsds)

**Comment by DeadSquirrel01** [comment]
This issue should be posted in blobs repo
