### ISSUE TITLE
Can't make or receive calls

### ISSUE THREAD

**Issue by knuxify** [DeadSquirrel01/android_device_samsung_a5-common#14]
I can't make or receive calls on my A500FU. The SIM card seems to be detected.

**Comment by mimminou** [comment]
Same issues ... ill redo the flash process whenever i have time and report some feedback...i have the 500fu and i skipped the mm modem part because i was already running mm stock...ill try doing that step later on
 [EDIT] 
i did reflash with and without gapps with mm modem and still can't recieve phonecalls while i can make them but can't hear anything within the call not even the hold beep..

**Comment by legitscoper** [comment]
Same here. Pls fix this

**Comment by knuxify** [comment]
Actually, I have noticed that the RIL libs in another ROM (RR Rom for A500H) have much more variety in the code, and calling features seems to work on the rom. As some of the things not working have been RIL and telephony, I think reviewing the other libraries would be a good idea. The only thing that would need a change is dual-sim features (note I'm mostly noting this as a solution for SMA500FU which has 1 sim slot, might help to other 1 sim slot model users as well). Sorry if RIL is irrevelant to this problem.
___
[Link to the libraries](https://github.com/Ahmed-Khalifa/android_device_samsung_a5-common/blob/cm-14.1/ril/SamsungA5RILv2.java)
[Link to an older version of the libraries, also might be worth checking](https://github.com/Ahmed-Khalifa/android_device_samsung_a5-common/blob/cm-14.1/ril/SamsungA5RIL.java)
___
EDIT: I forked the project and modified several values, as well as I updated the RIL file. I would be glad if anyone could compile it for me and see if it works.
[Forked project](https://github.com/knuxfanwin8/android_device_samsung_a5-common)

**Comment by legitscoper** [comment]
I will see if I can do it, I am on vacations so in like 3-5 days

**Comment by ergeka** [comment]
Hi,
Me too, I can't make or receive calls on my A500FU ...
Good vacations ;-)

**Comment by legitscoper** [comment]
@knuxfanwin8 my a5 broken down into pieces so I cannot test it. You must compile it for your own. Here is tutorial: https://forum.xda-developers.com/chef-central/android/how-to-build-lineageos-14-1-t3551484 and http://www.lineageosrom.com/2017/01/how-to-build-lineageos-rom-for-any.html. Idk which one is best. Good luck.

**Comment by knuxify** [comment]
Well, my laptop broke lately and I won't be able to compile it too :P
Anyway, I'll try to do something when my laptop gets fixed. 

_Sent from my Samsung SM-A500FU using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by legitscoper** [comment]
Well, I can try to compile it but I will have to send it to you and then you will have to download it and upload without compiling yourself

**Comment by knuxify** [comment]
@leitscoper yeah you can just compile it, I'll be more than happy to test it

_Sent from my Samsung SM-A500FU using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Confirm same problem, tried fixing using a build.prop edit, now phone not picking up my SIM card, known issue too, this is my daily driver for school/work/internet, please fix?

**Comment by DeadSquirrel01** [comment]
This issue should be posted on blobs repo. Anyway, the instructions are on XDA thread
