### ISSUE TITLE
Freezing phone on wake up screen

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [DeadSquirrel01/android_device_samsung_a5-common#15]
I've noticed that sometimes when I'm running my phone (SM-A500FU) then I can't unlock screen.
I don't know how to provide steps to reproduce this problem, it's very randomly. It's very frequently when my phone receives notifications or calls.

Sometimes when I've achieved unlocked screen on after freezing lock screen, the system doesn't react to most of touches. It then helps to turn off the screen, wait a few seconds, and turn the screen back on.

edit: It's same: 
- https://forum.xda-developers.com/showpost.php?p=73476168&postcount=306
- https://forum.xda-developers.com/showpost.php?p=73522230&postcount=344
- https://forum.xda-developers.com/showpost.php?p=73528071&postcount=347

**Comment by arkadiusz-wieczorek** [comment]
Edit: sometimes when I've achieved unlocked screen on after freezing lock screen, the system doesn't react to most of touches. It then helps to turn off the screen, wait a few seconds, and turn the screen back on.

**Comment by jplitza** [comment]
I have this problem not only on the lock screen, but it also persists after unlocking (if I manage to unlock it despite it ignoring most of the presses).

**Comment by arkadiusz-wieczorek** [comment]
@DeadSquirrel01 how can I help you for debugging this annoying issue?

**Comment by cdutsov** [comment]
I have the same issue. Very random touch screen lags on some unlocks of the screen

**Comment by jplitza** [comment]
This is solved in the newest release by the commits DeadSquirrel01/android_kernel_samsung_msm8916@7ebdf8ac704b15fa14c954f4f20ba26ddf817acb and following (I guess).

Although touching when the screen lights up after taking the phone out of the pocket but before pressing a button doesn't work anymore. But that's a fair price for having it respond in all other situations. ;-)

**Comment by DeadSquirrel01** [comment]
Fixed with https://github.com/DeadSquirrel01/android_device_samsung_a5-common/commit/5ed9135f4461bbac55e7c706c508a9c3f1078488
