### ISSUE TITLE
Camera, AudioFX

### ISSUE THREAD

**Issue by ProManiFest** [DeadSquirrel01/android_device_samsung_a5-common#2]
When i start filming immediately turns off. 
I do not know if this is bug, but AudioFX doesn't work. You can check this
I go looking for more bugs

**Comment by DeadSquirrel01** [comment]
Strange, AUDIOFX and camera both works, have you formatted data/cache/dalvik before flashing?

**Comment by ProManiFest** [comment]
I'll see maybe it's my fault

**Comment by ProManiFest** [comment]
Okey, I installed again system with yours modem and BL and AudioFX working, but i can't making videos i can only take photos

**Comment by DeadSquirrel01** [comment]
With can't record video bug, i agree :D

**Comment by ProManiFest** [comment]
The buttons below the screen react when phone be blocked

**Comment by ProManiFest** [comment]
or my phone have ADHD xdd

**Comment by DeadSquirrel01** [comment]
That's not a bug

**Comment by nonsocchi** [comment]
I'm having the same problem. I can't record videos and sound doesn't work on my phone. Also, my sim card doesn't work either.

**Comment by DeadSquirrel01** [comment]
AudioFX was working.
Camera that couldn't take videos is fixed with https://github.com/DeadSquirrel01/android_device_samsung_a5-common/commit/b648ca1e66bdd9a00c3d46e81ca07b6233f72a9a
I can close this now
