### ISSUE TITLE
Gps not accurate

### ISSUE THREAD

**Issue by GrizzlyErson** [DeadSquirrel01/android_device_samsung_a5-common#20]
Not accurate unlike the 4th release for a500f users and takes few seconds to lock in

**Comment by DeadSquirrel01** [comment]
Fixed in 5th release. Fix inside https://github.com/DeadSquirrel01/android_device_samsung_a5-common/commit/7d325b3ced3f97b2b2e9f38ec343fd6ae69c8aa5
