### ISSUE TITLE
Vibration

### ISSUE THREAD

**Issue by Enrique16C** [DeadSquirrel01/android_device_samsung_a5-common#21]
Vibration does not work on Samsung Galaxy a500w with Lineage OS.

**Comment by DeadSquirrel01** [comment]
This is not a problem of lineage. It happens because the kernel in my lineage is for FU, and some components, and so drivers, are different. These kind of issues should be reported on xda btw, as some did. I can close it now

**Comment by Enrique16C** [comment]
Thanks for your help.
