### ISSUE TITLE
Screen lock on call

### ISSUE THREAD

**Issue by patriksomodi** [DeadSquirrel01/android_device_samsung_a5-common#22]
Device: A500FU
The screen goes black on call (as it should), but the screen is not actually locked, the device responses to touch, so my flashlight always turns on for example.

**Comment by DeadSquirrel01** [comment]
I've tested right now and it worked as expected (screen black unresponsive). Inputdisabler stops the touch when screens goes black (except if you have tap2wake), but since tap2wake doesn't do nothing during calls, there should be no problems

**Comment by patriksomodi** [comment]
Well actually it was for the previous build, so i'll just close this
