### ISSUE TITLE
Mobile data doesn't work (A500FU)

### ISSUE THREAD

**Issue by knuxify** [DeadSquirrel01/android_device_samsung_a5-common#23]
When I turn on mobile data, the phone keeps acting like it's offline. It works rarely, and even if it does, it just randomly stops working again after some time. My model is A500FU.

**Comment by DeadSquirrel01** [comment]
I need to know: version of the rom (build date), kernel version and a "logcat -b radio"

**Comment by GrizzlyErson** [comment]
Yeah same here with a500f model i just notice the mobile data doesn't work sometimes you have to re enable the data again in order to work

**Comment by DeadSquirrel01** [comment]
Well, then it's not "it doesn't work" but just sometimes? On my device it happened only on first boot, but after rebooted it always worked. :/ anyway read my prev comment: "It doesn't work" means nothing

**Comment by GrizzlyErson** [comment]
"Doesn't work sometimes " i mean sometimes it stops receiving data until i re enable it.. Sorry for my bad english..

**Comment by DeadSquirrel01** [comment]
I meant I want the logcat. On my device I don't have that problem, so, it would be useless to check a logcat of my device's RIL

**Comment by knuxify** [comment]
My ROM version is 20170906, kernel version 3.10.106-lineageos. http://kfw8.ga/uploads/1507045984.txt logcat

**Comment by knuxify** [comment]
I'll try reverting to stock and re-install, I'll reply if it works

====EDIT====
Changed "force 4g" to "force 3g" in mobile data settings and it seems to work now. I guess it must be something with my 4g signal (which is generally low around the area I live in).

Issue closed.
