### ISSUE TITLE
SM-A5000 : SIM card not recognised

### ISSUE THREAD

**Issue by breversa** [DeadSquirrel01/android_device_samsung_a5-common#25]
As stated here : https://forum.xda-developers.com/showpost.php?p=73999557&postcount=408, the SIM card is not recognized for SM-A5000.

Here are both the libsec-ril.so and libsec-ril-dsds.so (not sure if needed as it's single-SIM only) files for SM-A5000. 

[SM-A5000.zip](https://github.com/DeadSquirrel01/android_device_samsung_a5-common/files/1347383/SM-A5000.zip)

**Comment by DeadSquirrel01** [comment]
This is not a bug of a5-common tree: not right place to post this

**Comment by breversa** [comment]
Is there a better place for that ?

**Comment by DeadSquirrel01** [comment]
Xda

**Comment by breversa** [comment]
https://forum.xda-developers.com/showpost.php?p=73999557&postcount=408
