### ISSUE TITLE
SM-A5000 : screen rotation if 90° off to the right

### ISSUE THREAD

**Issue by breversa** [DeadSquirrel01/android_device_samsung_a5-common#27]
As stated here : https://forum.xda-developers.com/showpost.php?p=73999557&postcount=408, rotation detection is 90° off to the right. When the phone is upright, display is tilted 90° to the right.

Workaround : disable screen autorotation.

**Comment by DeadSquirrel01** [comment]
You have to enable 180° rotation

**Comment by breversa** [comment]
Even if I enable 180° rotation in Settings/Display/Rotation settings, the phone keeps behaving anormally. I've tried several combination of (allowed) rotations, but none is satifsfactory.
