### ISSUE TITLE
Touchscreen controls itself or is not responding A500fu

### ISSUE THREAD

**Issue by ABC0815** [DeadSquirrel01/android_device_samsung_a5-common#28]
Hi,

I have the issue that my phone ( Galaxy A500fu) controls itself sometimes. It swipes notifications or even dials numbers when it is not locked with a code. Sometimes it also is not even responding at all. I can touch the display wherever I want but no reaction. I have to use the Power button a few times (to lock and wake up the phone) until I can control the phone again.

Is there any kind of fix for that?

I can tell that it is not any hardwareissue, because when I flash back to custom ROM the display works as it should.

**Comment by knuxify** [comment]
I have a similar issue. It fixes itself after locking and unlocking the
screen. Also, could you provide your ROM and kernel version?

**Comment by ABC0815** [comment]
Good I am not the only one. Yes it fixes itself but it is very annoying if the phone rings and You have to lock/unlock it 5times before You can answer :/

AS ROM I got: 14.1-2070822-UNOFFICIAL-a5ultexx
My Kernel is:
3.10.106 lineageos
Marco@gentoo #1
Tue Aug 22

Hope this is what You asked for.

**Comment by DeadSquirrel01** [comment]
You aren't on latest version. If the problem persist on latest version, feel free to reopen

**Comment by NunzioP** [comment]
Hello I have te same problem.
The rom is the latest 14.1-20170906-unofficial-a5ultexx.
I hope you can fix.
