### ISSUE TITLE
Sim not detected

### ISSUE THREAD

**Issue by ghost** [DeadSquirrel01/android_device_samsung_a5-common#4]
Imei s are still shown
Mine a500g

**Comment by DeadSquirrel01** [comment]
Have you replaced libsecril.so and if it is multisim also libsecril-dsds.so from stock rom with the one(s) in recovery? (If it is multisim you have to add in build.prop alsopersist.radio.multisim.config=dsds)

**Comment by ghost** [comment]
I'm not exactly sure on how to do that
Could u explain?

**Comment by ghost** [comment]
Sounds aren't heard too (completely)

**Comment by DeadSquirrel01** [comment]
These steps are shown in main thread, you can't create an issue before at least reading the thead. I think can close this issue now

**Comment by ghost** [comment]
I just read the entire thread
The reason I posted was bcos no one had reported the sim not being detected
I installed twrp with Odin
Made a backup
Cleared all data
Installed ROM
Flashed superuser and gapps
Did I do something wrong or miss something?
This is my first attempt at installing custom ROMs and would really
appreciate some help
I tried restoring back to the stock system a couple of times and things
were quite normal and no issues detected there
Here, I don't think even sound works(not even through headphones)
Just getting vibration feedback
I could wait for a fix but I really like cm and need ATLEAST call
functionality
Thanks for the time and sorry for the long message

**Comment by DeadSquirrel01** [comment]
There are lots of guides on how to install custom roms and stock roms, i don't want to wate my time to write someone you can see just if you search 'how to flash stock rom' on google. Regarding no sound during call is a bug but headphonws should work. If you find this rom too bugged for your daily use you can simple install stock rom (or if you didn't want to waste your time installing this, you could read bug section)
