### ISSUE TITLE
emergency calls only on SM A500H

### ISSUE THREAD

**Issue by nonsocchi** [DeadSquirrel01/android_device_samsung_a5-common#6]
It shows sim card not detected.  Pls how can I fix this. Is there a patch I can flash?

**Comment by DeadSquirrel01** [comment]
Have you copied /system/lib/libsecril.so from stock ROM? This is shown in instructions. Please read them before posting bugs. If it still doesn't work please reply

**Comment by DeadSquirrel01** [comment]
Well, you reported it in bug section, while it is not a bug. These things should ne asked in help sections like the thread or on IRC. So, I think I can close it now

**Comment by RemonAbdelmalak** [comment]
I cant find libsecril.so
It only shows libsecril-client.so 
Is that is ?!

**Comment by nonsocchi** [comment]
No. Those are 2 separate files. Take a look at this.
