### ISSUE TITLE
Hardware navbar breaking occasionally

### ISSUE THREAD

**Issue by Natrocx** [DeadSquirrel01/android_device_samsung_a5-common#7]
The hardware navbar is breaking ocaasionally; that means that only the home button can be used anymore. The back and recents keys aren't working/lit. 
The error occurs after the phone was "sleeping" (screen turned off) for a while. For me only reproducable when letting the phone lay around somewhere when i.e. sleeping.
My workaround for this was to activate the soft keys in build.prop.

**Comment by DeadSquirrel01** [comment]
Hmm, weird. On my device they works well. What device are you using. I'll wait for someone which can confirm this

**Comment by Natrocx** [comment]
I am on sm-a500fu 
Though I might have to switch the rom today because of bugs concerning the dialing if reflashing doesn't help.

**Comment by legitscoper** [comment]
I am also on a-500fu and they sometimes stop working.  Did not notice when but it is annoying
