### ISSUE TITLE
Sim Card Not Detected 

### ISSUE THREAD

**Issue by RemonAbdelmalak** [DeadSquirrel01/android_device_samsung_a5-common#8]
Please can you tell me how to fix this bug 
I read how to install the cm14.1 but i didnt understand and can you tell me what to do step by step thanks for reading

**Comment by DeadSquirrel01** [comment]
This bug regards your device's blobs not the a5-common tree

**Comment by RemonAbdelmalak** [comment]
Sorry but what do you mean with "device's blobs ?!
