### ISSUE TITLE
Unknown Baseband

### ISSUE THREAD

**Issue by iijhay2** [DeadSquirrel01/android_device_samsung_a5-common#9]
When i flash the rom . the baseband will be unknown , imei will become null . i read the instructions carefully . i copy the libsecril . i also did backup the modem and efs from twrp from stock and restore it in cm14.1 but still didnt work . sm-a500L here.

**Comment by DeadSquirrel01** [comment]
Hey, your device needs to be here: 
https://github.com/DeadSquirrel01/android_device_samsung_a5ultexx/blob/cm-14.1/init/init_a5lte.cpp
Add it with its informations, that should fix baseband problem

**Comment by iijhay2** [comment]
Done adding my device info.  whats next ? how will i apply it on my device ?

**Comment by knuxify** [comment]
You would have to compile the code to apply it. I forked the code and someone will maybe try to compile it, so your info should be present in the build
